// Generated by CoffeeScript 1.4.0

/*global FSS:true, FLB:true, _gaq:true
*/


(function() {

  window.onload = function() {
    var flb, fss, gaTrack, lightbox, lightboxes, navClickHandler, navItem, navItems, postTweet, slideshow, slideshows, trackClickHandler, trackElems, _i, _j, _k, _len, _len1, _len2;
    if (!document.querySelector) {
      return;
    }
    slideshows = document.querySelectorAll('#hero_slideshow .slideshow');
    if (slideshows.length) {
      for (_i = 0, _len = slideshows.length; _i < _len; _i++) {
        slideshow = slideshows[_i];
        fss = new FSS(slideshow, {
          width: 725,
          height: 210
        });
      }
    }
    lightboxes = document.querySelectorAll('a[rel=simplebox]');
    if (lightboxes.length) {
      for (_j = 0, _len1 = lightboxes.length; _j < _len1; _j++) {
        lightbox = lightboxes[_j];
        flb = new FLB(lightbox, {});
      }
    }
    navClickHandler = function(elem, navItems) {
      return function() {
        var a, item, projectItem, projectItems, _k, _l, _len2, _len3;
        a = elem.getAttribute('rel');
        for (_k = 0, _len2 = navItems.length; _k < _len2; _k++) {
          item = navItems[_k];
          if (item.className.match(new RegExp('(\\s|^)' + 'active' + '(\\s|$)'))) {
            item.className = item.className.replace(new RegExp('(\\s|^)' + 'active' + '(\\s|$)'), '');
          }
        }
        projectItems = document.querySelectorAll('#projects_list li');
        for (_l = 0, _len3 = projectItems.length; _l < _len3; _l++) {
          projectItem = projectItems[_l];
          if (projectItem.className.match(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'))) {
            projectItem.className = projectItem.className.replace(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'), '');
          }
          if (a !== 'all' && !projectItem.className.match(new RegExp('(\\s|^)' + a + '(\\s|$)'))) {
            if (!projectItem.className.match(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'))) {
              projectItem.className += ' ' + 'deselected';
            }
          }
        }
        elem.className = ' ' + 'active';
      };
    };
    if (document.querySelector('#p72')) {
      navItems = document.querySelectorAll('#projects-nav dd');
      for (_k = 0, _len2 = navItems.length; _k < _len2; _k++) {
        navItem = navItems[_k];
        navItem.onclick = navClickHandler(navItem, navItems);
      }
    }
    postTweet = document.querySelector('#post-tweet');
    if (postTweet) {
      postTweet.onclick = function() {
        var centerLeft, centerTop;
        gaTrack('Tweet Post', this.firstChild.nodeValue, document.title);
        centerLeft = window.screen.width / 2 - 550 / 2;
        centerTop = window.screen.height / 2 - 470 / 2;
        window.open(this.href, this.getAttribute("target"), 'width=550, height=470, location=0, left=' + centerLeft + ', top=' + centerTop);
        return false;
      };
    }
    trackElems = function(elems, cat, action, label) {
      var elem, _l, _len3;
      if (!elems) {
        return;
      }
      for (_l = 0, _len3 = elems.length; _l < _len3; _l++) {
        elem = elems[_l];
        elem.onclick = trackClickHandler(elem, cat, action, label);
      }
      return false;
    };
    trackClickHandler = function(elem, cat, action, label) {
      var actn;
      actn = action ? elem.querySelector(action).firstChild.nodeValue : elem.firstChild.nodeValue;
      return function() {
        gaTrack(cat, actn, label);
        if (elem.getAttribute("target")) {
          window.open(this.href, this.getAttribute("target"));
        } else {
          setTimeout('document.location = "' + elem.href + '"', 150);
        }
        return false;
      };
    };
    gaTrack = function(cat, action, label, val) {
      try {
        _gaq.push(['_trackEvent', cat, action, label, val]);
      } catch (error) {
        print(error);
      }
      return false;
    };
    trackElems(document.querySelectorAll('#menu-primary a'), 'Top Nav', null, document.title);
    trackElems(document.querySelectorAll('#bio_pic'), 'Bio Pic', null, document.title);
    trackElems(document.querySelectorAll('#prev-post a'), 'Previous Post', '.arrow', document.title);
    trackElems(document.querySelectorAll('#download_follow a.twitter, #download_follow a.rss'), 'Projects Follow', null, document.title);
    trackElems(document.querySelectorAll('#other_projects #projects_list a'), 'Other Projects', 'small', document.title);
    trackElems(document.querySelectorAll('#footer_main_promo'), 'Footer Promo', '.header', document.title);
    trackElems(document.querySelectorAll('#text-12 .recommended a'), 'Recommended', null, document.title);
    trackElems(document.querySelectorAll('#page-footer #twitter-follow a.button'), 'Footer Twitter', null, document.title);
  };

  window.error = function(message, file, line) {
    _gaq.push(['_trackEvent', 'Exceptions', 'Application', '[' + file + ' (' + line + ')] ' + message, null, true]);
  };

  /*
  function getOffset( el ) {
  		var _x = 0;
  		var _y = 0;
  		while( el && !isNaN( el.offsetLeft ) && !isNaN( el.offsetTop ) ) {
  				_x += el.offsetLeft - el.scrollLeft;
  				_y += el.offsetTop - el.scrollTop;
  				el = el.offsetParent;
  		}
  		return { top: _y, left: _x };
  }
  var x = getOffset( document.getElementById('yourElId') ).left;
  */


}).call(this);
