// Generated by CoffeeScript 1.3.3
/*global FSS:true, FLB:true, _gaq:true, console:true
*/

window.onload = function() {
  var flb, fss, gaTrack, lightbox, lightboxes, navClickHandler, navItem, navItems, postTweet, slideshow, slideshows, trackClickHandler, trackElems, _i, _j, _k, _len, _len1, _len2;
  if (!document.querySelector) {
    return;
  }
  navClickHandler = function(elem, navItems) {
    return function() {
      var a, item, projectItem, projectItems, _i, _j, _len, _len1;
      a = elem.getAttribute('rel');
      elem.className += ' active';
      for (_i = 0, _len = navItems.length; _i < _len; _i++) {
        item = navItems[_i];
        if (item.className.match(new RegExp('(\\s|^)' + 'active' + '(\\s|$)'))) {
          item.className = item.className.replace(new RegExp('(\\s|^)' + 'active' + '(\\s|$)'), '');
        }
      }
      projectItems = document.querySelectorAll('#projects_list li');
      for (_j = 0, _len1 = projectItems.length; _j < _len1; _j++) {
        projectItem = projectItems[_j];
        if (projectItem.className.match(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'))) {
          projectItem.className = projectItem.className.replace(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'), '');
        }
        if (a !== 'all' && !projectItem.className.match(new RegExp('(\\s|^)' + a + '(\\s|$)'))) {
          if (!projectItem.className.match(new RegExp('(\\s|^)' + 'deselected' + '(\\s|$)'))) {
            projectItem.className += ' ' + 'deselected';
          }
        }
      }
    };
  };
  trackClickHandler = function(elem, cat, action, label) {
    return function() {
      gaTrack(cat, action ? elem.querySelector(action).firstChild.nodeValue : elem.firstChild.nodeValue);
      if (elem.getAttribute("target")) {
        window.open(this.href, this.getAttribute("target"));
      } else {
        setTimeout('document.location = "' + elem.href + '"', 100);
      }
      return false;
    };
  };
  trackElems = function(elems, cat, action, label) {
    var elem, _i, _len;
    if (!elems) {
      return;
    }
    for (_i = 0, _len = elems.length; _i < _len; _i++) {
      elem = elems[_i];
      elem.onclick = trackClickHandler(elem, cat, action, label);
    }
    return false;
  };
  gaTrack = function(cat, action, label, val) {
    try {
      _gaq.push(['_trackEvent', cat, action, label, val]);
    } catch (error) {
      print(error);
    }
  };
  slideshows = document.querySelectorAll('#hero_slideshow .slideshow');
  if (slideshows.length) {
    for (_i = 0, _len = slideshows.length; _i < _len; _i++) {
      slideshow = slideshows[_i];
      fss = new FSS(slideshow, {
        width: 725,
        height: 210
      });
    }
  }
  lightboxes = document.querySelectorAll('a[rel=simplebox]');
  if (lightboxes.length) {
    for (_j = 0, _len1 = lightboxes.length; _j < _len1; _j++) {
      lightbox = lightboxes[_j];
      flb = new FLB(lightbox, {});
    }
  }
  if (document.querySelector('#p72')) {
    navItems = document.querySelectorAll('#projects_navigation dd');
    for (_k = 0, _len2 = navItems.length; _k < _len2; _k++) {
      navItem = navItems[_k];
      navItem.onclick = navClickHandler(navItem, navItems);
    }
  }
  postTweet = document.querySelector('#post_tweet');
  if (postTweet) {
    postTweet.onclick = function(e) {
      var centerLeft, centerTop;
      gaTrack('Tweet Post', this.firstChild.nodeValue, document.title);
      centerLeft = window.screen.width / 2 - 550 / 2;
      centerTop = window.screen.height / 2 - 470 / 2;
      window.open(this.href, this.getAttribute("target"), 'width=550, height=470, location=0, left=' + centerLeft + ', top=' + centerTop);
      return false;
    };
  }
  trackElems(document.querySelectorAll('#menu-primary li a'), 'Top Nav', null, document.title);
  trackElems(document.querySelectorAll('#bio_pic'), 'Bio Pic', null, document.title);
  trackElems(document.querySelectorAll('#previous_post a'), 'Previous Post', '.arrow', document.title);
  trackElems(document.querySelectorAll('#download_follow a.twitter, #download_follow a.rss'), 'Projects Follow', null, document.title);
  trackElems(document.querySelectorAll('#other_projects #projects_list li a'), 'Other Projects', 'small', document.title);
  trackElems(document.querySelectorAll('#footer_main_promo'), 'Footer Promo', '.header', document.title);
  trackElems(document.querySelectorAll('#text-12 .recommended a'), 'Recommended', null, document.title);
  trackElems(document.querySelectorAll('#page_footer #twitter_follow a.button'), 'Footer Twitter', null, document.title);
};

window.error = function(message, file, line) {
  _gaq.push(['_trackEvent', 'Exceptions', 'Application', '[' + file + ' (' + line + ')] ' + message, null, true]);
};

/*
function getOffset( el ) {
		var _x = 0;
		var _y = 0;
		while( el && !isNaN( el.offsetLeft ) && !isNaN( el.offsetTop ) ) {
				_x += el.offsetLeft - el.scrollLeft;
				_y += el.offsetTop - el.scrollTop;
				el = el.offsetParent;
		}
		return { top: _y, left: _x };
}
var x = getOffset( document.getElementById('yourElId') ).left;
*/

