/*
		GNU/GPL license: http://www.gnu.org/copyleft/gpl.html
*/
function frank_slideshow(a,b){if(document.querySelectorAll){var e=document.querySelectorAll(a);if(e)for(var f=0;f<e.length;f++)new FSS(e[f],b)}}function FSS(a,b){"[object Object]"===Object.prototype.toString.call(b)&&(this.opt=b);this.con=a;this.slds=[];this.nv;this.cpt;this.ci=-1;this.opt.width||(this.opt.width=this.con.offsetWidth);this.opt.height||(this.opt.height=this.con.offsetHeight);this.to;this.autoplay=!0;this.dur=5E3;this.init(a);this.gotoslide(0);this.autoplay&&this.play()}
FSS.prototype.init=function(a){var b=this;this.con.style.width=this.opt.width+"px";this.con.style.height=this.opt.height+"px";this.con.className.match(/(\s|^)fss(\s|$)/)||(this.con.className+=" fss");if(a.hasChildNodes){c=a.firstChild;for(a=0;c;)c&&3!=c.nodeType&&this.slds.push({ndx:a++,el:c.childNodes}),c=c.nextSibling;this.nv=document.createElement("ul");a=document.createAttribute("class");a.nodeValue="fss-nav";this.nv.setAttributeNode(a);for(a=0;a<this.slds.length;a++){var e=document.createElement("li");
e.appendChild(document.createTextNode(""+(a+1)));e.onclick=function(){b.navclick(this)};this.nv.appendChild(e)}this.con.appendChild(this.nv);this.cpt=document.createElement("div");a=document.createAttribute("class");a.nodeValue="fss-caption";this.cpt.setAttributeNode(a);this.con.parentNode.insertBefore(this.cpt,this.con.nextSibling);this.con.onmouseover=function(a){if(a){if(a.target!=b.con)return a.cancelBubble=!0,a.stopPropagation(),!1;b.pause();b.nv.className.match(/(\s|^)active(\s|$)/)||(b.nv.className+=
" active")}};this.con.onmouseout=function(a){if(a){if(b.ischild(a.relatedTarget,b.con))return a.cancelBubble=!0,a.stopPropagation(),!1;b.play();b.nv.className.match(/(\s|^)active(\s|$)/)&&(b.nv.className=b.nv.className.replace(/(\s|^)active(\s|$)/,""))}}}};FSS.prototype.ischild=function(a,b){if(b===a)return!1;for(;a&&a!==b;)a=a.parentNode;return a===b};FSS.prototype.autoNext=function(a){a&&(a.next(),a.play())};FSS.prototype.next=function(){this.gotoslide(this.ci<this.slds.length-1?this.ci+1:0)};
FSS.prototype.navclick=function(a){this.pause();for(var b=0;this.nv.childNodes.item(b);){if(this.nv.childNodes.item(b)==a){this.gotoslide(b);break}b++}};
FSS.prototype.gotoslide=function(a){if(this.ci!=a){this.con.style.backgroundPosition=""+-1*this.opt.width*a+"px 0px";var b=this.nv.querySelector(".active");b&&b.removeAttribute("class");b=document.createAttribute("class");b.nodeValue="active";for(this.nv.childNodes.item(a).setAttributeNode(b);this.cpt.hasChildNodes();)this.cpt.removeChild(this.cpt.firstChild);for(b=0;b<this.slds[a].el.length;b++)this.cpt.appendChild(this.slds[a].el.item(b).cloneNode(!0));this.ci=a}};FSS.prototype.pause=function(){clearTimeout(this.to)};
FSS.prototype.play=function(){clearTimeout(this.to);this.to=setTimeout(this.autoNext,this.dur,this)};var sbLoaderSide=100,resizeImage=1,imgDisplayDelay=600,sbOverlayId="jwSBoverlay",sbContainerId="jwSBcontainer",sbContentId="jwSBcontent",sbImageId="jwSBimage",sbImageAlt="Preview...",sbCaptionId="sbcaption",sbButtonCloseId="jwSBclose",sbCloseTitle="Click anywhere on the screen to close the image...",isIE6=-1!=navigator.userAgent.toLowerCase().indexOf("msie 6");
function simpleBox(){if(!document.getElementsByTagName||!document.getElementById)return!1;for(var a=document.getElementsByTagName("a"),b=0;b<a.length;b++)/simplebox/.test(a[b].getAttribute("rel"))&&(a[b].onclick=function(){var a=this.getAttribute("href"),b=this.getAttribute("title");b||(b="Images from the article "+document.title);buildImgPopup(a,b);return!1})}
function buildImgPopup(a,b){var e=document.createElement("div");e.setAttribute("id",sbOverlayId);if(isIE6){document.getElementsByTagName("html")[0].style.overflow="hidden";var f=document.documentElement.clientWidth+"px",l=document.documentElement.clientHeight+"px"}e.innerHTML='<div id="'+sbContainerId+'" style="width:'+f+";height:"+l+';"><a href="#" title="'+sbCloseTitle+'" class="closingElement">&nbsp;</a></div><div id="'+sbContentId+'"><a id="'+sbImageId+'" class="closingElement" href="#" title="'+
sbCloseTitle+'"></a><span id="'+sbCaptionId+'">'+b+'</span><a id="'+sbButtonCloseId+'" class="closingElement" href="#" title="'+sbCloseTitle+'">&nbsp;</a></div>';document.getElementsByTagName("body")[0].appendChild(e);var i=document.getElementById(sbContentId);i.style.width=sbLoaderSide+"px";i.style.height=sbLoaderSide+"px";i.style.margin="-"+sbLoaderSide/2+"px 0 0 -"+sbLoaderSide/2+"px";isIE6&&(e.style.top=document.documentElement.scrollTop+"px",i.style.top=document.documentElement.clientHeight/
2+"px",i.style.position="absolute");var g=document.getElementById(sbImageId);g.style.background="url("+a+") no-repeat 50% 50%";g.style.display="none";var h=document.getElementById(sbCaptionId);h.style.display="none";var d=new Image;d.onload=function(){if(resizeImage){var a=document.documentElement.clientHeight-40;d.height<a?(imgHeight=d.height,imgWidth=d.width):(imgHeight=a,imgWidth=Math.round(a*d.width/d.height),d.height=imgHeight,d.width=imgWidth)}else imgHeight=d.height,imgWidth=d.width;setTimeout(function(){i.style.background=
"#060606"},300);setTimeout(function(){i.style.width=imgWidth+"px";i.style.height=imgHeight+"px";i.style.margin="-"+(imgHeight+28)/2+"px 0 0 -"+imgWidth/2+"px"},600);setTimeout(function(){g.style.display="block";h.style.display=""},900)};d.src=a;f=e.getElementsByTagName("a");for(l=0;l<f.length;l++)"closingElement"==f[l].className&&(f[l].onclick=function(){e.style.display="none";document.getElementsByTagName("body")[0].removeChild(e);isIE6&&(document.getElementsByTagName("html")[0].style.overflow="");
return!1})}function addLoadEvent(a){var b=window.onload;window.onload="function"!=typeof window.onload?a:function(){b&&b();a()}}addLoadEvent(simpleBox);
window.onload=function(){function a(a,b,d){a&&(a.onclick=function(){var a=d?this.querySelector(d).firstChild.nodeValue:this.firstChild.nodeValue;try{_gaq.push(["_trackEvent",b,a,document.title,void 0])}catch(e){}setTimeout('document.location = "'+this.href+'"',100);return!1})}function b(a,b,d,e){if(a)for(h=0;h<a.length;h++)a[h].onclick=function(){var a=d?this.querySelector(d).firstChild.nodeValue:this.firstChild.nodeValue;try{_gaq.push(["_trackEvent",b,a,e,void 0])}catch(f){}setTimeout('document.location = "'+
this.href+'"',100);return!1}}if(document.querySelector){var e=document.createElement("style"),f=document.createAttribute("type");f.nodeValue="text/css";e.setAttributeNode(f);var l=document.createTextNode("a{ -webkit-transition-property: background-color, color; -webkit-transition-duration: .3s; -webkit-transition-timing-function: cubic-bezier(0.02, 0, 0.18, 1.0); -moz-transition-property: background, color; -moz-transition-duration: .3s; -moz-transition-timing-function: cubic-bezier(0.02, 0, 0.18, 1.0); -o-transition-property: background, color; -o-transition-duration: .3s; -o-transition-timing-function: cubic-bezier(0.02, 0, 0.18, 1.0); }");
document.getElementsByTagName("head").item(0).appendChild(e);try{e.appendChild(l)}catch(i){}frank_slideshow("#hero_slideshow .slides",{width:725,height:210});simpleBox();if(document.querySelector("#p72")){var g,h,d,j,k,m;g=document.querySelectorAll("#projects_navigation dd");for(h=0;h<g.length;h++)e=g[h],e.onclick=function(){g=document.querySelectorAll("#projects_navigation dd");f=this.getAttribute("rel");for(d=0;d<g.length;d++)m=g[d].getAttribute("rel"),m!=f?g[d].className.match(/(\s|^)active(\s|$)/)&&
(g[d].className=g[d].className.replace(/(\s|^)active(\s|$)/,"")):g[d].className.match(/(\s|^)active(\s|$)/)||(g[d].className+=" active");k=document.querySelectorAll("#projects_list li");for(j=0;j<k.length;j++)k[j].className.match(/(\s|^)deselected(\s|$)/)&&(k[j].className=k[j].className.replace(/(\s|^)deselected(\s|$)/,"")),"all"!=f&&!k[j].className.match(RegExp("(\\s|^)"+f+"(\\s|$)"))&&!k[j].className.match(/(\s|^)deselected(\s|$)/)&&(k[j].className+=" deselected")}}b(document.querySelectorAll("#menu-primary li a"),
"Top Nav",null,document.title);a(document.querySelector("#bio_pic"),"Bio Pic",null,document.title);a(document.querySelector("#content.single .post-info .previous a"),"Previous Post",".arrow",document.title);b(document.querySelectorAll("#download_follow a.twitter, #download_follow a.rss"),"Projects Follow",null,document.title);b(document.querySelectorAll("#other_projects #projects_list li a"),"Other Projects","small",document.title);a(document.querySelector("#footer_main_promo"),"Footer Promo",".header",
document.title);b(document.querySelectorAll("#text-12 .recommended a"),"Recommended",null,document.title);a(document.querySelector("#page_footer #twitter_follow a.button"),"Footer Twitter",null,document.title)}};
