var FSS;
FSS=function(){function c(a,e){this.element=a;this.options="[object Object]"===Object.prototype.toString.call(e)?e:{};this.init();this.gotoslide(0);this.autoplay&&this.play()}var g,f,h,i,d,b;c.prototype.pause=function(){clearTimeout(this.interval)};c.prototype.play=function(){clearTimeout(this.interval);this.interval=setTimeout(g,this.duration,this)};c.prototype.next=function(){this.gotoslide(this.currentIndex<this.slides.length-1?this.currentIndex+1:0)};c.prototype.gotoslide=function(a){var e;this.currentIndex!==
a&&((e=this.element.parentNode.querySelector(".visible"))&&e===this.slideA?(this.slideB.style.backgroundPosition="0px "+-1*this.options.height*a+"px",this.slideA.className=this.slideA.className.replace(/(\s|^)visible(\s|$)/,""),this.slideB.className+=" visible"):(this.slideA.style.backgroundPosition="0px "+-1*this.options.height*a+"px",this.slideB.className=this.slideB.className.replace(/(\s|^)visible(\s|$)/,""),this.slideA.className+=" visible"),(e=this.navigation.querySelector(".active"))&&e.removeAttribute("class"),
e=document.createAttribute("class"),e.nodeValue="active",this.navigation.childNodes.item(a).setAttributeNode(e),e=-1===this.currentIndex?0:this.currentIndex,this.slides[e].el.className=this.slides[e].el.className.replace(/(\s|^)active(\s|$)/,""),this.slides[a].el.className+=" active",this.currentIndex=a)};c.prototype.init=function(){var a,e,j,c,k;e=this;this.options.width||(this.options.width=this.element.offsetWidth);this.options.height||(this.options.height=this.element.offsetHeight);this.autoplay=
!0;this.duration=5E3;this.currentIndex=-1;this.element.className.match(/(\s|^)fss(\s|$)/)||(this.element.className+=" fss");if(this.caption=this.element.querySelector(".captions")){a=this.caption.firstChild;c=0;for(this.slides=[];a;)a&&3!==a.nodeType&&this.slides.push({ndx:c++,el:a}),a=a.nextSibling;this.container=f("div","slide-container");this.slideA=f("div","slide-a visible");this.slideB=f("div","slide-b");this.element.insertBefore(this.container,this.caption);this.container.appendChild(this.slideA);
this.container.appendChild(this.slideB);this.slideA.style.width=this.slideB.style.width=this.options.width+"px";this.slideA.style.height=this.slideB.style.height=this.options.height+"px";this.navigation=f("ul","fss-nav");j=this.slides;a=c=0;for(k=j.length;c<k;a=++c)j=f("li"),j.appendChild(document.createTextNode(""+(a+1))),this.navigation.appendChild(j),j.onclick=b(j,this);this.container.appendChild(this.navigation);this.container.onmouseover=function(a){return d(a,e)};this.container.onmouseout=function(a){return i(a,
e)}}};f=function(a,e){var b,d;d=document.createElement(a);if(!e)return d;b=document.createAttribute("class");b.nodeValue=e;d.setAttributeNode(b);return d};h=function(a,e){if(a===e)return!1;for(;a&&a!==e;)a=a.parentNode;return a===e};g=function(a){a&&(a.next(),a.play())};b=function(a,e){return function(){var b;e.pause();for(b=0;e.navigation.childNodes.item(b);){if(e.navigation.childNodes.item(b)===a){e.gotoslide(b);break}b++}}};d=function(a,e){if(a){if(!h(a.target,e.container))return a.cancelBubble=
!0,a.stopPropagation(),!1;e.pause();e.navigation.className.match(/(\s|^)active(\s|$)/)||(e.navigation.className+=" active")}};i=function(a,e){if(h(a.relatedTarget,e.container))return a.cancelBubble=!0,a.stopPropagation(),!1;e.play();e.navigation.className.match(/(\s|^)active(\s|$)/)&&(e.navigation.className=e.navigation.className.replace(/(\s|^)active(\s|$)/,""))};return c}();var FLB;
FLB=function(){function c(d,b){this.element=d;this.options="[object Object]"===Object.prototype.toString.call(b)?b:{};this.options.resizeImage=!1;this.init()}var g,f,h,i;c.sbLoaderSide=null;c.resizeImage=null;c.imgDisplayDelay=null;c.sbOverlayId=null;c.element=null;c.options=null;c.image=null;c.container=null;c.overlay=null;c.imgContainer=null;c.prototype.init=function(){var d;d=this;this.element.onclick=function(b){return g(b,d)}};c.prototype.createOverlay=function(d){var b;b=this;this.overlay=document.createElement("div");
this.overlay.setAttribute("id","flb-overlay");this.overlay.innerHTML='<div id="flb-container"><a href="#" title="Close" class="closingElement">&nbsp;</a></div><div id="flb-content"><a id="flb-image" class="closingElement" href="#" title="Close"></a><a id="flb-close" class="closingElement" href="#" title="Close">&nbsp;</a></div>';document.getElementsByTagName("body")[0].appendChild(this.overlay);this.container=document.getElementById("flb-content");this.container.style.width="100px";this.container.style.height=
"100px";this.container.style.margin="-50px 0 0 -50px";this.container.onclick=this.overlay.onclick=function(a){return f(a,b)};this.imgContainer=document.getElementById("flb-image");this.imgContainer.style.background="url("+d+") no-repeat 50% 50%";this.image=new Image;this.image.onload=function(a){return h(a,b)};this.image.src=d};h=function(d,b){var a,e,c;b.options.resizeImage?(c=document.documentElement.clientHeight-40,b.image.height<c?(a=b.image.height,e=b.image.width):(a=c,e=Math.round(c*b.image.width/
b.image.height),b.image.height=a,b.image.width=e)):(a=b.image.height,e=b.image.width);setTimeout(function(){return i(b.container,e,a)},600)};i=function(d,b,a){d.style.width=b+"px";d.style.height=a+"px";d.style.margin="-"+(a+28)/2+"px 0 0 -"+b/2+"px";d.setAttribute("class","active")};g=function(d,b){b.createOverlay(d.target.getAttribute("href"));d.cancelBubble=!0;d.stopPropagation();return!1};f=function(d,b){b.container.setAttribute("class","");document.getElementsByTagName("body")[0].removeChild(b.overlay)};
return c}();
window.onload=function(){var c,g,f,h,i,d,b,a;if(document.querySelector){h=function(a,b){return function(){var d,c,f,g,h;d=a.getAttribute("rel");a.className+=" active";f=0;for(g=b.length;f<g;f++)c=b[f],c.className.match(/(\s|^)active(\s|$)/)&&(c.className=c.className.replace(/(\s|^)active(\s|$)/,""));f=document.querySelectorAll("#projects_list li");g=0;for(h=f.length;g<h;g++)if(c=f[g],c.className.match(/(\s|^)deselected(\s|$)/)&&(c.className=c.className.replace(/(\s|^)deselected(\s|$)/,"")),"all"!==
d&&!c.className.match(RegExp("(\\s|^)"+d+"(\\s|$)"))&&!c.className.match(/(\s|^)deselected(\s|$)/))c.className+=" deselected"}};i=function(a,b,d){return function(){c(b,d?a.querySelector(d).firstChild.nodeValue:a.firstChild.nodeValue);setTimeout('document.location = "'+a.href+'"',100);return!1}};d=function(a,b,c,d){var f,g,h;if(a){g=0;for(h=a.length;g<h;g++)f=a[g],f.onclick=i(f,b,c,d);return!1}};c=function(a,b,c,d){try{_gaq.push(["_trackEvent",a,b,c,d])}catch(f){print(f)}};f=document.querySelectorAll("#hero_slideshow .slideshow");
if(f.length){b=0;for(a=f.length;b<a;b++)g=f[b],new FSS(g,{width:725,height:210})}f=document.querySelectorAll("a[rel=simplebox]");if(f.length){b=0;for(a=f.length;b<a;b++)g=f[b],new FLB(g,{})}if(document.querySelector("#p72")){f=document.querySelectorAll("#projects_navigation dd");b=0;for(a=f.length;b<a;b++)g=f[b],g.onclick=h(g,f)}d(document.querySelectorAll("#post_tweet"),"Tweet Post",null,document.title);d(document.querySelectorAll("#menu-primary li a"),"Top Nav",null,document.title);d(document.querySelectorAll("#bio_pic"),
"Bio Pic",null,document.title);d(document.querySelectorAll("#previous_post a"),"Previous Post",".arrow",document.title);d(document.querySelectorAll("#download_follow a.twitter, #download_follow a.rss"),"Projects Follow",null,document.title);d(document.querySelectorAll("#other_projects #projects_list li a"),"Other Projects","small",document.title);d(document.querySelectorAll("#footer_main_promo"),"Footer Promo",".header",document.title);d(document.querySelectorAll("#text-12 .recommended a"),"Recommended",
null,document.title);d(document.querySelectorAll("#page_footer #twitter_follow a.button"),"Footer Twitter",null,document.title)}};window.error=function(c,g,f){_gaq.push(["_trackEvent","Exceptions","Application","["+g+" ("+f+")] "+c,null,!0])};
